server:
  port: 5003

spring:
  application:
    name: getRand_datacollectionservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/getrand?serverTimezone=Asia/Seoul
    username: mytest
    password: 1234

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    # 2초동안 하트비트가 수신되지 않으면 서비스 등록을 해제
    lease-expiration-duration-in-seconds: 2

serp:
  api-key: bd471ed09868f3f7f787aca90100e0ef547d588900f4832cb94aea8282388f23

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace